services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=tasks_db
      - POSTGRES_PASSWORD=8744821jk99ww@13
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - tasks_network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_db/postgres:/var/lib/postgresql/data
  server:
    container_name: tasks
    image: tasks:server
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/tasks/tasks
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - tasks_network


volumes:
  postgres_db:

networks:
  tasks_network: