# Generated by Django 5.1.2 on 2024-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_timing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time_working",
            name="hours_working",
        ),
        migrations.AddField(
            model_name="time_working",
            name="hours_worked",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="time_working",
            name="hours_working_in",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="time_working",
            name="hours_working_out",
            field=models.DateTimeField(null=True),
        ),
    ]
