# Generated by Django 5.1.2 on 2024-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_timing", "0004_timeworking_delete_time_working"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeworking",
            name="date",
        ),
        migrations.AlterField(
            model_name="timeworking",
            name="hours_working_in",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
