# Generated by Django 5.1.2 on 2024-10-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_timing", "0006_alter_timeworking_job_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
